<a href="https://colab.research.google.com/github/tecnojimbo/G5-ANALISISDATOS-EDA-/blob/dev-janzules/G5-AnalisisDatos-EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Reporte Ejecutivo: Segmentación de Clientes Utilizando Análisis RFM

## Resumen Ejecutivo

Este reporte presenta un análisis exhaustivo de la base de clientes de la empresa utilizando la metodología RFM (Recencia, Frecuencia, Monetario). El objetivo principal es segmentar a los clientes en grupos homogéneos basados en su comportamiento de compra, lo que permitirá implementar estrategias de marketing más efectivas y personalizadas. Hemos identificado cinco segmentos clave: 'Campeones', 'Clientes Leales', 'Leales Potenciales', 'En Riesgo' y 'Clientes Perdidos', cada uno con características distintivas en términos de actividad y valor. Las visualizaciones y métricas detalladas a continuación ofrecen una visión clara del perfil de cada segmento y resaltan oportunidades para la retención y el crecimiento.

## 1. Carga y Preparación de Datos

El primer paso crucial en cualquier análisis es la carga y limpieza de los datos. Se cargaron los datos de ventas y se realizaron varias transformaciones para asegurar la calidad y el formato adecuado para el análisis RFM.

### 1.1. Importación de Librerías y Carga Inicial

---

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

customerData = pd.read_csv('/content/Analytical Customer Segmentation Analysis(in).csv', encoding='latin1')

### 1.2. Exploración Inicial de Datos

---

In [4]:
print('Primeras 5 filas:')
display(customerData.head(5))

print('\nÚltimas 5 filas:')
display(customerData.tail(5))

print('\nValores nulos por columna:')
display(customerData.isnull().sum())

print('\nTipos de datos actuales:')
display(customerData.info())

Primeras 5 filas:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,01/12/2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6.0,01/12/2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,01/12/2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,01/12/2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,01/12/2010 08:26,3.39,17850.0,United Kingdom

Últimas 5 filas:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
74221,542408,22439,6 ROCKET BALLOONS,10.0,27/01/2011 16:29,0.65,13280.0,United Kingdom
74222,542408,20726,LUNCH BAG WOODLAND,10.0,27/01/2011 16:29,1.65,13280.0,United Kingdom
74223,542408,20728,LUNCH BAG CARS BLUE,10.0,27/01/2011 16:29,1.65,13280.0,United Kingdom
74224,542408,22384,LUNCH BAG PINK POLKADOT,10.0,27/01/2011 16:29,1.65,13280.0,United Kingdom
74225,542,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Valores nulos por columna:

InvoiceNo          0
StockCode       1188
Description     1372
Quantity        1188
InvoiceDate     1188
UnitPrice       1188
CustomerID     28602
Country         1188
dtype: int64

Tipos de datos actuales:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74226 entries, 0 to 74225
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    74226 non-null  object
 1   StockCode    73038 non-null  object
 2   Description  72854 non-null  object
 3   Quantity     73038 non-null  float64
 4   InvoiceDate  73038 non-null  object
 5   UnitPrice    73038 non-null  float64
 6   CustomerID   45624 non-null  float64
 7   Country      73038 non-null  object
dtypes: float64(3), object(5)
memory usage: 4.5+ MB

None